# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6cff7cb930d62e2e5f158687cd636bf3504e6f4a5874e4bbf9efb1dbc1fd1e2276bbd7c762b41c0de2fc24b2eb8aa933b99f644bf36c8239c41025494a0f1017

test:
  secret_key_base: e41b796a77d5701994cf2c01a98ac5e104fc61e27d3ad133320fe03822c5b31951ede8028d5a4c0ed0a654e5985d6283103f272b65d627af7ebff1f1e8e3d4b3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
